### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by gopi-03** [DBeath/testing-flask-tutorial#1]
I'm using windows 8.1 and python version is 3.6.1
I don't why it is not working. create_app is function is not in below directories of tests directory.
It is in above directory of conf.test directory. I think that is the real problem. Rest of them I can manage.
Please let me know how to import `upper directory modules into lower directory modules.`

```
$ pytest tests/
Traceback (most recent call last):
  File "c:\users\sys\appdata\local\programs\python\python36-32\lib\site-packages\_pytest\config.py", line 336, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('C:\\Users\\Sys\\Downloads\\testing-flask-tutorial-master\\tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\users\sys\appdata\local\programs\python\python36-32\lib\site-packages\_pytest\config.py", line 367, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('C:\\Users\\Sys\\Downloads\\testing-flask-tutorial-master\\tests\\conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\users\sys\appdata\local\programs\python\python36-32\lib\site-packages\_pytest\config.py", line 373, in _importconftest
    mod = conftestpath.pyimport()
  File "c:\users\sys\appdata\local\programs\python\python36-32\lib\site-packages\py\_path\local.py", line 662, in pyimport
    __import__(modname)
  File "c:\users\sys\appdata\local\programs\python\python36-32\lib\site-packages\_pytest\assertion\rewrite.py", line 215, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "C:\Users\Sys\Downloads\testing-flask-tutorial-master\tests\conftest.py", line 2, in <module>
    from application.core import create_app
  File "C:\Users\Sys\Downloads\testing-flask-tutorial-master\application\core.py", line 2, in <module>
    from application.frontend import frontend_blueprint
  File "C:\Users\Sys\Downloads\testing-flask-tutorial-master\application\frontend\__init__.py", line 8, in <module>
    from application.frontend.views import index
  File "C:\Users\Sys\Downloads\testing-flask-tutorial-master\application\frontend\views.py", line 3, in <module>
    from application.frontend.models import User, user_schema
  File "C:\Users\Sys\Downloads\testing-flask-tutorial-master\application\frontend\models.py", line 2, in <module>
    from marshmallow_sqlalchemy import ModelSchema
ModuleNotFoundError: No module named 'marshmallow_sqlalchemy'
ERROR: could not load C:\Users\Sys\Downloads\testing-flask-tutorial-master\tests\conftest.py

```

**Comment by DBeath** [comment]
You're getting that error because you haven't installed the `marshmallow-sqlalchemy` package. Install all the packages listed in `requirements.txt`, and then the tests should run.
